# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  CURRENT_VERSION: 0.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin gh-pages --depth=1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: git config user.name ci-bot
      - run: git config user.email ci-bot@example.com
      - run: mike delete -b gh-pages $CURRENT_VERSION
        continue-on-error: true
      - run: mike set-default -b gh-pages $CURRENT_VERSION
      - run: mike deploy -b gh-pages --push $CURRENT_VERSION
